### ISSUE TITLE
Refreshed tokens in middleware aren't propagated from server back to the client

### ISSUE THREAD

**Issue by skyerus** [urboifox/nextjs-refreshtoken-demo#2]
[Here](https://github.com/urboifox/nextjs-refreshtoken-demo/blob/main/src/middleware.ts#L51), the refreshed access token cookie is sent back in the response. But, the cookie isn't applied to the client, because the fetch doesn't handle the returned cookies (e.g. [here](https://github.com/urboifox/nextjs-refreshtoken-demo/blob/main/src/app/profile/page.tsx#L12).

I've tried adding

```
 const cookieStore = await cookies()
    response.headers.getSetCookie()?.forEach(cookie => {
        const [name, value] = cookie.split(';')[0].split('=')
        cookieStore.set(name, value)
    })
```

to the result of the fetch but that just gives the error

```
unhandledRejection: Error: Cookies can only be modified in a Server Action or Route Handler. Read more: https://nextjs.org/docs/app/api-reference/functions/cookies#options
```

**Comment by urboifox** [comment]
I totally forgot what this method was about :D it was just a POC.

I don't think this repo is valid anymore, too much boilerplate to put in a real app. specially after next 15.

But as i got more experience in next.js, i found out that the best way to do this is to just create a wrapper function around fetch.

maybe call it something like `fetcher()`

and make your interecpting code there, this is simpler and only one file, instead of modifying a lot of files like in this repo.
That's what im working with currently on multiple projects🙌🏼

Thank you for opening an issue, I almost forgot this repo, I will maybe archive it and add some notes in the readme.
